### ISSUE TITLE
build fail at 'KanjiViewer.assertAnimationParameters' method

### ISSUE THREAD

**Issue by tokyokamera** [acaziasoftcom/flutter_kanji_view#1]
I have a problem as below. How can I fix this?

I/flutter ( 9046): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9046): The following assertion was thrown building Playground(dirty, dependencies: [TickerMode], state:
I/flutter ( 9046): _PlaygroundState#79fa6(ticker inactive)):
I/flutter ( 9046): 'package:flutter_kanji_view/fklib/drawing_widget.dart': Failed assertion: line 241 pos 12:
I/flutter ( 9046): '!(this.controller == null &&
I/flutter ( 9046):         (this.run == null || this.duration == null))': is not true.
I/flutter ( 9046): 
I/flutter ( 9046): 
I/flutter ( 9046): When the exception was thrown, this was the stack:
I/flutter ( 9046): #2      KanjiViewer.assertAnimationParameters (package:flutter_kanji_view/fklib/drawing_widget.dart:241:12)
I/flutter ( 9046): #3      new KanjiViewer.svg (package:flutter_kanji_view/fklib/drawing_widget.dart:94:5)
I/flutter ( 9046): #4      _PlaygroundState.build (package:flutter_kanji/main.dart:62:32)
I/flutter ( 9046): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4440:27)
I/flutter ( 9046): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4329:15)
I/flutter ( 9046): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #76     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #86     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #98     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #111    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #114    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5684:32)
I/flutter ( 9046): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 9046): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter ( 9046): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9046): #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9046): #136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter ( 9046): #137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9046): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9046): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9046): #140    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════

**Comment by Doko-Demo-Doa** [comment]
@tokyokamera Can you show me your code snippets?

**Comment by Doko-Demo-Doa** [comment]
Close due to inactivity.
